config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :users 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    User.create(user_params)
    redirect_to root_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:name, :age, :number_of_coffee)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coffeecounter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1> How much coffee do you drink? </h1>
<%= link_to "coffee counter", new_user_path %>
<h1><% @users.inspect %></h1>
<br/>

<% @users.each do |user| %>
  <div>
    <i> Name: <%= user.name %></i><br/>
    <i>Age:   <%= user.age %></i><br />
    <i>Coffee cups per day: <%= user.number_of_coffee %></i><br />
  </div>

  <hr />
<% end %>

app/views/users/new.html.erb
<h1> Enter the amount of coffee you drink per day </h1>
  <%= simple_form_for @user do |f| %>
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :number_of_coffee %>
    <%= f.submit 'submit' %>
  <% end %>
